export const keywordList = [
  // Personal Care & Beauty
  "moisturizer",
  "face wash",
  "shampoo",
  "conditioner",
  "serum",
  "sunscreen",
  "lip balm",
  "face cream",
  "cleanser",
  "toner",
  "body wash",
  "hair oil",
  "night cream",
  "eye cream",
  "facial oil",
  "face mask",
  "body scrub",
  "hair serum",
  "hair mask",
  "beard oil",

  // Electronics
  "mobiles",
  "smartphones",
  "tablets",
  "laptops",
  "televisions",
  "headphones",
  "earphones",
  "wireless earbuds",
  "bluetooth speakers",
  "smart watches",
  "power banks",
  "phone chargers",
  "phone cases",
  "usb cables",
  "gaming mouse",
  "mechanical keyboards",
  "routers",
  "webcams",
  "SSD",
  "hard disks",

  // Home & Kitchen Appliances
  "air conditioners",
  "refrigerators",
  "washing machines",
  "microwave ovens",
  "kitchen chimneys",
  "induction cooktops",
  "water purifiers",
  "vacuum cleaners",
  "ceiling fans",
  "geysers",
  "hair dryers",
  "hair straighteners",
  "mixers",
  "grinders",
  "electric kettles",
  "toasters",
  "sandwich makers",
  "dishwashers",
  "air fryers",
  "rice cookers",

  // Fashion
  "men's shoes",
  "women's shoes",
  "men’s t-shirts",
  "women’s tops",
  "men’s jeans",
  "women’s jeans",
  "watches for men",
  "watches for women",
  "sunglasses for men",
  "sunglasses for women",
  "backpacks",
  "handbags",
  "wallets",
  "belts",
  "sports shoes",
  "ethnic wear women",
  "kurta men",
  "activewear",
  "jackets",
  "slippers",

  // Fitness & Health
  "protein powder",
  "yoga mats",
  "dumbbells",
  "resistance bands",
  "massagers",
  "weighing scales",
  "fitness trackers",
  "multivitamins",
  "gym gloves",
  "cycling helmets"
];